apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../initial

patches:
  - target: 
      kind: Deployment
      name: test
    patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value: 
          new: this will cause a redeploy
  - target:
      kind: StatefulSet
      name: test-statefulset
    patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value:
          new: this will cause statefulset to redeploy
